baseURL = "https://psuastro528.github.io/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Astro 528: HPC for Astrophysics"
theme = "docdock"
#themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
markup = "markdown"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

sectionPagesMenu = "main"

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
#editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = true

BookShowToC = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[menu]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<img src='http://socialmedia.psu.edu/files/2015/09/psu-avatar-no_containing_shape-285x300.png' height='90%'> <label>ACI Portal</label>"
identifier = "aci portal"
url = "http://portal.aci.ics.psu.edu"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> <label>Github</label>"
identifier = "github-org"
url = "https://github.com/PsuAstro528"
weight = 20

#[[menu.shortcuts]]
#name = "<i class='fa fa-cloud-download'></i> <label>DockDoc theme</label>"
#url = "https://github.com/vjeantet/hugo-theme-docdock/"
#weight = 130

#[[menu.shortcuts]]
#name = "<i class='fa fa-bookmark'></i> <label>Hugo</label>"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 120

#[[menu.shortcuts]]
#name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
#url = "/credits"
#weight = 190


